---
fontsize: 12
geometry: margin=3cm

link-citations: yes
citecolor: blue
linkcolor: blue
csl: templates/apa.csl

output:
  pdf_document:
    includes:
      in_header: templates/header.tex

bibliography: templates/packages.bib
classoption: twoside

nocite: |
 | @Croissant2008, @Bache2014a, @Xie2016, @Xie2014, @Hester2016a, @Hlavac2015
 | @Garnier2017a, @Wickham2017a, @Allaire2017a, @Wickham2016, @Chan2016a, @Wickham2016b
 | @Wickham2009, @Kahle2013, @Schloerke2016, @Xie2015, @Wickham2016c, @Robinson2017a,
 | @Zeileis2002, @Bivand2016a, @Gagolewski2017a, @RCoreTeam2016a
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      error = FALSE, cache = 2)
knitr::opts_knit$set(root.dir = '/home/devvart/Dropbox/Hertie/HealthandCrime')
```

\setcounter{page}{26}

# Appendix

## Note on Codes and Data

The entire paper was written in, and with the help of, R. The codes for downloading the data, cleaning, merging and finally presenting are all open source and available at [Github](https://github.com/devvartpoddar/HealthandCrime).

## Urbanisation codes

\begin{table}[!htbp] \centering 
  \caption{Overview of urbanisation codes in the US} 
  \label{} 
\begin{tabular}{@{\extracolsep{2pt}} ccl} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
RUCC 2013 Codes & Collapsed Codes & Description \\ 
\hline \\[-1.8ex] 
$1$ & $1$ & Counties in metro areas of 1 million population or more \\ 
$2$ & $2$ & Counties in metro areas of 250,000 to 1 million population \\ 
$3$ & $3$ & Counties in metro areas of fewer than 250,000 population \\ 
$4$ & $4$ & Urban population of 20,000 or more, adjacent to a metro area \\ 
$5$ & $5$ & Urban population of 20,000 or more, not adjacent to a metro area \\ 
$6$ & $4$ & Urban population of 2,500 to 19,999, adjacent to a metro area \\ 
$7$ & $5$ & Urban population of 2,500 to 19,999, not adjacent to a metro area \\ 
$8$ & $6$ & Completely rural or less than 2,500 urban population, \\
& & adjacent to a metro area \\ 
$9$ & $6$ & Completely rural or less than 2,500 urban population, \\
& & not adjacent to a metro area \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table} 
\newpage

## R Packages